# https://finnhub.io/api/v1/quote?symbol=AAPL&token=d43arkpr01qvk0jb1gtgd43arkpr01qvk0jb1gu0
# https://finnhub.io/api/v1/stock/profile2?symbol=AAPL&token=d43arkpr01qvk0jb1gtgd43arkpr01qvk0jb1gu0
api-service:
  finnhub:
    api-token: 'd43arkpr01qvk0jb1gtgd43arkpr01qvk0jb1gu0'
    host: 'finnhub.io'
    endpoints:
      quote:
        version: '/api/v1'
        endpoint: '/quote'
      profile2:
        version: '/api/v1'
        endpoint: '/stock/profile2'
